package main

import (
	"time"

	"github.com/nurulislamz/agentusage/internal/core"
)

func buildCodexDemoSnapshot(now time.Time) core.UsageSnapshot {
	return core.UsageSnapshot{
		ProviderID: "codex",
		AccountID:  "codex-cli",
		Timestamp:  now,
		Status:     core.StatusLimited,
		Metrics: map[string]core.Metric{
			"rate_limit_primary":               {Used: ptr(18), Limit: ptr(100), Remaining: ptr(82), Unit: "%", Window: "5h"},
			"rate_limit_secondary":             {Used: ptr(100), Limit: ptr(100), Remaining: ptr(0), Unit: "%", Window: "7d"},
			"rate_limit_code_review_primary":   {Used: ptr(2), Limit: ptr(100), Remaining: ptr(98), Unit: "%", Window: "7d"},
			"rate_limit_code_review_secondary": {Used: ptr(0), Limit: ptr(100), Remaining: ptr(100), Unit: "%", Window: "7d"},
			"plan_auto_percent_used":           {Used: ptr(18), Limit: ptr(100), Remaining: ptr(82), Unit: "%", Window: "5h"},
			"plan_api_percent_used":            {Used: ptr(100), Limit: ptr(100), Remaining: ptr(0), Unit: "%", Window: "7d"},
			"plan_percent_used":                {Used: ptr(100), Limit: ptr(100), Remaining: ptr(0), Unit: "%", Window: "7d"},
			"context_window":                   {Used: ptr(10400000), Limit: ptr(258400), Unit: "tokens"},
			"composer_context_pct":             {Used: ptr(100), Unit: "%", Window: "all-time"},
			"credit_balance":                   {Used: ptr(42.6), Unit: "USD", Window: "current"},
			"session_cached_tokens":            {Used: ptr(7320000), Unit: "tokens", Window: "session"},
			"session_input_tokens":             {Used: ptr(10800), Unit: "tokens", Window: "session"},
			"session_output_tokens":            {Used: ptr(121300), Unit: "tokens", Window: "session"},
			"session_reasoning_tokens":         {Used: ptr(40600), Unit: "tokens", Window: "session"},
			"session_total_tokens":             {Used: ptr(10500000), Unit: "tokens", Window: "session"},

			"model_gpt_5_4_input_tokens":     {Used: ptr(9450000), Unit: "tokens", Window: "30d"},
			"model_gpt_5_4_output_tokens":    {Used: ptr(1160000), Unit: "tokens", Window: "30d"},
			"model_gpt_5_4_cached_tokens":    {Used: ptr(403000), Unit: "tokens", Window: "30d"},
			"model_gpt_5_4_reasoning_tokens": {Used: ptr(165000), Unit: "tokens", Window: "30d"},
			"model_gpt_5_4_total_tokens":     {Used: ptr(11178000), Unit: "tokens", Window: "30d"},

			"client_cli_total_tokens":     {Used: ptr(11178000), Unit: "tokens", Window: "30d"},
			"client_cli_input_tokens":     {Used: ptr(9450000), Unit: "tokens", Window: "30d"},
			"client_cli_output_tokens":    {Used: ptr(1160000), Unit: "tokens", Window: "30d"},
			"client_cli_cached_tokens":    {Used: ptr(403000), Unit: "tokens", Window: "30d"},
			"client_cli_reasoning_tokens": {Used: ptr(165000), Unit: "tokens", Window: "30d"},
			"client_cli_sessions":         {Used: ptr(11), Unit: "sessions", Window: "30d"},
			"client_cli_requests":         {Used: ptr(92), Unit: "requests", Window: "30d"},

			"project_dashboard_shell_requests":       {Used: ptr(41), Unit: "requests", Window: "30d"},
			"project_context_router_requests":        {Used: ptr(39), Unit: "requests", Window: "30d"},
			"project_infra_workers_requests":         {Used: ptr(9), Unit: "requests", Window: "30d"},
			"project_scratch_repro_a_requests":       {Used: ptr(2), Unit: "requests", Window: "30d"},
			"project_scratch_repro_b_requests":       {Used: ptr(1), Unit: "requests", Window: "30d"},
			"project_dashboard_shell_requests_today": {Used: ptr(14), Unit: "requests", Window: "1d"},

			"tool_exec_command":                           {Used: ptr(2931), Unit: "calls", Window: "30d"},
			"tool_write_stdin":                            {Used: ptr(398), Unit: "calls", Window: "30d"},
			"tool_apply_patch":                            {Used: ptr(314), Unit: "calls", Window: "30d"},
			"tool_update_plan":                            {Used: ptr(34), Unit: "calls", Window: "30d"},
			"tool_mcp_linear_list_issues":                 {Used: ptr(29), Unit: "calls", Window: "30d"},
			"tool_web_search":                             {Used: ptr(16), Unit: "calls", Window: "30d"},
			"tool_mcp_playwright_browser_take_screenshot": {Used: ptr(13), Unit: "calls", Window: "30d"},
			"tool_mcp_playwright_browser_navigate":        {Used: ptr(11), Unit: "calls", Window: "30d"},
			"tool_mcp_playwright_browser_resize":          {Used: ptr(11), Unit: "calls", Window: "30d"},
			"tool_mcp_kubernetes_resources_list":          {Used: ptr(6), Unit: "calls", Window: "30d"},
			"tool_view_image":                             {Used: ptr(6), Unit: "calls", Window: "30d"},
			"tool_mcp_playwright_browser_snapshot":        {Used: ptr(5), Unit: "calls", Window: "30d"},

			// ── MCP servers ───────────────────────────────────────
			"mcp_calls_total":       {Used: ptr(68), Unit: "calls", Window: "30d"},
			"mcp_calls_total_today": {Used: ptr(6), Unit: "calls", Window: "1d"},
			"mcp_servers_active":    {Used: ptr(4), Unit: "servers", Window: "30d"},

			"mcp_linear_total":         {Used: ptr(39), Unit: "calls", Window: "30d"},
			"mcp_linear_total_today":   {Used: ptr(6), Unit: "calls", Window: "1d"},
			"mcp_linear_list_issues":   {Used: ptr(29), Unit: "calls", Window: "30d"},
			"mcp_linear_save_issue":    {Used: ptr(3), Unit: "calls", Window: "30d"},
			"mcp_linear_list_statuses": {Used: ptr(3), Unit: "calls", Window: "30d"},

			"mcp_codex_apps_total":                      {Used: ptr(16), Unit: "calls", Window: "30d"},
			"mcp_codex_apps_total_today":                {Used: ptr(2), Unit: "calls", Window: "1d"},
			"mcp_codex_apps_github_create_pull_request": {Used: ptr(4), Unit: "calls", Window: "30d"},
			"mcp_codex_apps_github_search":              {Used: ptr(3), Unit: "calls", Window: "30d"},
			"mcp_codex_apps_github_get_issue":           {Used: ptr(2), Unit: "calls", Window: "30d"},

			"mcp_kubernetes_total":           {Used: ptr(10), Unit: "calls", Window: "30d"},
			"mcp_kubernetes_total_today":     {Used: ptr(0), Unit: "calls", Window: "1d"},
			"mcp_kubernetes_resources_list":  {Used: ptr(6), Unit: "calls", Window: "30d"},
			"mcp_kubernetes_pods_log":        {Used: ptr(1), Unit: "calls", Window: "30d"},
			"mcp_kubernetes_namespaces_list": {Used: ptr(1), Unit: "calls", Window: "30d"},

			"mcp_gopls_total":          {Used: ptr(3), Unit: "calls", Window: "30d"},
			"mcp_gopls_total_today":    {Used: ptr(0), Unit: "calls", Window: "1d"},
			"mcp_gopls_go_diagnostics": {Used: ptr(3), Unit: "calls", Window: "30d"},

			"tool_calls_total":  {Used: ptr(3745), Unit: "calls", Window: "30d"},
			"tool_completed":    {Used: ptr(3539), Unit: "calls", Window: "30d"},
			"tool_errored":      {Used: ptr(192), Unit: "calls", Window: "30d"},
			"tool_cancelled":    {Used: ptr(14), Unit: "calls", Window: "30d"},
			"tool_success_rate": {Used: ptr(94.5), Unit: "%", Window: "30d"},

			"lang_go":   {Used: ptr(1), Unit: "requests", Window: "30d"},
			"lang_json": {Used: ptr(2), Unit: "requests", Window: "30d"},
			"lang_yaml": {Used: ptr(1), Unit: "requests", Window: "30d"},

			"total_ai_requests":       {Used: ptr(92), Unit: "requests", Window: "30d"},
			"composer_requests":       {Used: ptr(92), Unit: "requests", Window: "30d"},
			"requests_today":          {Used: ptr(14), Unit: "requests", Window: "today"},
			"today_composer_requests": {Used: ptr(14), Unit: "requests", Window: "today"},
			"composer_sessions":       {Used: ptr(11), Unit: "sessions", Window: "30d"},
			"total_prompts":           {Used: ptr(68), Unit: "prompts", Window: "30d"},
			"composer_lines_added":    {Used: ptr(276), Unit: "lines", Window: "30d"},
			"composer_lines_removed":  {Used: ptr(5), Unit: "lines", Window: "30d"},
			"composer_files_changed":  {Used: ptr(14), Unit: "files", Window: "30d"},
			"scored_commits":          {Used: ptr(1), Unit: "commits", Window: "30d"},
			"ai_code_percentage":      {Used: ptr(100), Unit: "%", Window: "30d"},
			"ai_deleted_files":        {Used: ptr(0), Unit: "files", Window: "30d"},
			"ai_tracked_files":        {Used: ptr(14), Unit: "files", Window: "30d"},
		},
		Resets: map[string]time.Time{
			"rate_limit_primary":               now.Add(4*time.Hour + 59*time.Minute),
			"rate_limit_secondary":             now.Add(3*24*time.Hour + 20*time.Hour),
			"rate_limit_code_review_primary":   now.Add(7 * 24 * time.Hour),
			"rate_limit_code_review_secondary": now.Add(7 * 24 * time.Hour),
		},
		Raw: map[string]string{
			"account_email":  "anon.codex.user@example.invalid",
			"account_id":     "anon-codex-team-01",
			"plan_type":      "team",
			"cli_version":    "0.105.0",
			"credit_balance": "$42.60",
			"model_usage":    "gpt-5.4 100%",
			"client_usage":   "CLI 100%",
			"project_usage":  "dashboard_shell: 41 req, context_router: 39 req, infra_workers: 9 req, scratch_repro_a: 2 req",
			"tool_usage":     "exec_command 79%, write_stdin 11%, apply_patch 8%, update_plan 1%, web_search <1%",
			"language_usage": "go 100%",
		},
		DailySeries: map[string][]core.TimePoint{
			"analytics_cost":                demoPatternSeries(now, 0, demoPatternCodexSparse...),
			"analytics_tokens":              demoPatternSeries(now, 7680041, demoPatternCodexSparse...),
			"analytics_requests":            demoPatternSeries(now, 64, demoPatternCodexSparse...),
			"tokens_total":                  demoPatternSeries(now, 7680041, demoPatternCodexSparse...),
			"requests":                      demoPatternSeries(now, 64, demoPatternCodexSparse...),
			"tokens_client_cli":             demoPatternSeries(now, 7680041, demoPatternCodexSparse...),
			"usage_client_cli":              demoPatternSeries(now, 64, demoPatternCodexSparse...),
			"usage_source_cli":              demoPatternSeries(now, 64, demoPatternCodexSparse...),
			"usage_model_gpt_5_4":           demoPatternSeries(now, 64, demoPatternCodexSparse...),
			"usage_project_dashboard_shell": demoPatternSeries(now, 22, demoPatternCodexSparse...),
			"usage_project_context_router":  demoPatternSeries(now, 39, demoPoint(1, 1.0)),
			"usage_project_infra_workers":   demoPatternSeries(now, 9, demoPoint(6, 1.0)),
			"usage_project_scratch_repro_a": demoPatternSeries(now, 2, demoPoint(0, 1.0)),
		},
		Message: "Codex live usage + local session data",
	}
}
